### ISSUE TITLE
Events with "event_target:" in the option and events that follow them are not processed

### ISSUE THREAD

**Issue by grotaclas** [HairyDude/pdxparse#19]
I used pdxparse on the 1.29.6 version of eu4 and many event files were missing from the output and from others only parts of the events were generated. There was no error message about that.
To me it seems that the problem is caused by events which contain "event_target:" in one of the options. For example corruption_event.9 from CorruptionEvents.txt contains the option
```
option = {
    name = "corruption_event.9.a"
    add_prestige = -10
    event_target:culture_province = {
        add_local_autonomy = 10
    }
}
```
Then this event and all subsequent events in the file are not processed. Removing the event_target-block from this option and the other option which contains it, makes pdxparse process the events successfully.

For reference the following event files seem to be completely missing from the output:
ArmyProfessionalism.txt, ChineseFactions.txt, ConsortEvents.txt, CulturalUprising.txt, Industrialization.txt, InvestmentEvents.txt, Japan.txt, MamlukEvents.txt, MinorityExpulsionEvents.txt, MonsoonEvents.txt, MuslimSchoolEvents.txt, OrderEvents.txt, OrthodoxIcons.txt, Patriarchs.txt, PropagateReligionEvents.txt, RussianPrincipalities.txt, RussianTsardom.txt, SiberianColonization.txt, TradePolicyEvents.txt, TribalFederationEvents.txt

And the following files are missing the mentioned event and the following events(this was generated with a crude script, so some of them might be false positives):
Anglican_events.txt: anglican_events.8
ColonialNation.txt: colonial_nation.12
Confucianism.txt: confucian_events.14
Coptic.txt: coptic_flavor.32
CorruptionEvents.txt: corruption_event.9
CultureandReligionEvents.txt: culture_religion_events.3
Dynastic.txt: 9454
Elections.txt: elections.800
Espionage.txt: espionage_events.8
Fetishist.txt: fetishist_flavor.5
HaremEvents.txt: harem_events.3
Innovativeness.txt: innovativeness_events.3
MuslimDLC.txt: muslim_dlc.27
MuslimPietyEvents.txt: muslim_piety.12
PersonalityEvents.txt: personality_events.33
PriceChanges.txt: prices.31
RandomEvents.txt: 737
Shinto.txt: shinto_events.3
Streltsy.txt: streltsy_events.2
SubjectInteractionEvents.txt: subject_interaction_events.40
TradeLeague.txt: trade_league.9
TributaryEvents.txt: tributary_events.5
disaster_Revolution.txt: revolution.13
disaster_TUR_JanissaryDecadence.txt: janissary_decadence.5
disaster_court_and_country.txt: court_and_country_events.2
disaster_ming_crisis.txt: ming_crisis.6
estate_brahmins.txt: brahmins_estate_events.7
estate_marathas.txt: marathas_estate_events.6
estate_rajput.txt: rajputs_estate_events.5
estate_vaisyas.txt: vaisyas_estate_events.3
flavorDAN.txt: flavor_dan.10
flavorDaimyo.txt: flavor_daimyo.4
flavorHUN.txt: flavor_hun.19
flavorKOR.txt: flavor_kor.9
flavorMCH.txt: flavor_mch.5
flavorNOR.txt: flavor_nor.26
flavorZAN.txt: flavor_zan.5
institutions.txt: institution_events.22
pretty_colonial_borders.txt: pretty_colonial_borders.3
steppe_flavor.txt: randomeventsstapehordes.4

**Comment by HairyDude** [comment]
I'm fairly sure this is already fixed in my private copy. I haven't pushed in some time because I've been doing extensive refactoring. Let's see if I can get it into a pushable state.
